import { Injectable } from '@angular/core';
import { FuelProduct, Nutrition, ProductQuantities } from './product.model';

export const EMPTY_NUTRITION: Nutrition = {
  calories: 0,
  carbs: 0,
  sugar: 0,
  fiber: 0,
  fat: 0,
  protein: 0,
  sodium: 0,
  caffeine: 0,
  salt: 0,
  potassium: 0,
  magnesium: 0,
  calcium: 0,
};

const PRODUCTS: ReadonlyArray<FuelProduct> = [
  {
    id: 'maurten-gel-100-caf-100',
    brand: 'Maurten',
    name: 'Gel 100 Caf 100',
    kind: 'gel',
    serving: '1 sachet, 40 g',
    sourceLabel: 'Maurten',
    sourceUrl: 'https://www.maurten.com/products/us/gel-100-caf-100-box-us',
    nutrition: {
      ...EMPTY_NUTRITION,
      calories: 100,
      carbs: 25,
      sugar: 25,
      salt: 0.055,
      sodium: 22,
      caffeine: 100,
    },
  },
  {
    id: 'maurten-gel-160',
    brand: 'Maurten',
    name: 'Gel 160',
    kind: 'gel',
    serving: '1 sachet, 65 g',
    sourceLabel: 'Maurten',
    sourceUrl: 'https://www.maurten.com/products/gb/gel-160',
    nutrition: {
      ...EMPTY_NUTRITION,
      calories: 160,
      carbs: 40,
      sugar: 40,
      salt: 0.08,
      sodium: 32,
    },
  },
  {
    id: 'maurten-drink-mix-320-caf-100',
    brand: 'Maurten',
    name: 'Drink Mix 320 Caf 100',
    kind: 'drink',
    serving: '1 sachet in 500 ml, 83 g',
    sourceLabel: 'Maurten',
    sourceUrl: 'https://www.maurten.com/products/us/drink-mix-320-caf-100-us',
    nutrition: {
      ...EMPTY_NUTRITION,
      calories: 320,
      carbs: 80,
      sugar: 37,
      salt: 0.63,
      sodium: 250,
      caffeine: 100,
    },
  },
  {
    id: 'maurten-solid-160',
    brand: 'Maurten',
    name: 'Solid 160',
    kind: 'solid',
    serving: '1 bar, 55 g',
    sourceLabel: 'Maurten',
    sourceUrl: 'https://www.maurten.com/products/mt/solid-160',
    nutrition: {
      ...EMPTY_NUTRITION,
      calories: 199,
      carbs: 40,
      sugar: 17.5,
      fiber: 1.4,
      fat: 3.1,
      protein: 2.2,
      salt: 0.62,
      sodium: 244,
    },
  },
  {
    id: 'maurten-solid-c-160',
    brand: 'Maurten',
    name: 'Solid C 160',
    kind: 'solid',
    serving: '1 bar, 55 g',
    sourceLabel: 'Maurten',
    sourceUrl: 'https://www.maurten.com/products/cz/solid-c-160',
    nutrition: {
      ...EMPTY_NUTRITION,
      calories: 204,
      carbs: 40,
      sugar: 19.4,
      fiber: 2.2,
      fat: 3.2,
      protein: 2.6,
      salt: 0.62,
      sodium: 244,
    },
  },
  {
    id: 'baouw-puree-raspberry-strawberry-basil',
    brand: 'Baouw',
    name: 'Energy Purée Raspberry Strawberry Basil',
    kind: 'puree',
    serving: '1 purée, 90 g',
    sourceLabel: 'Baouw',
    sourceUrl:
      'https://www.baouw-organic-nutrition.com/en_GB/shop/energy-puree-bio-raspberry-strawberry-basil-891',
    nutrition: {
      ...EMPTY_NUTRITION,
      calories: 62,
      carbs: 11,
      sugar: 9.3,
      fiber: 0.3,
      fat: 1.8,
      protein: 0.3,
      salt: 0.03,
      sodium: 1,
      potassium: 150,
      magnesium: 18,
      calcium: 36,
    },
  },
  {
    id: 'baouw-electrolytes-blackberry',
    brand: 'Baouw',
    name: 'Electrolytes Blackberry Blackcurrant',
    kind: 'electrolyte',
    serving: '1 tablet in 500 ml, 5 g',
    sourceLabel: 'Baouw',
    sourceUrl:
      'https://www.baouw-organic-nutrition.com/en_GB/shop/electrolyte-blackberry-blackcurrant-1238',
    nutrition: {
      ...EMPTY_NUTRITION,
      calories: 11,
      carbs: 1.5,
      sugar: 0.03,
      fiber: 0.019,
      fat: 0,
      protein: 0.006,
      salt: 0.759,
      sodium: 300,
      potassium: 300,
      magnesium: 56.25,
      calcium: 50,
    },
  },
  {
    id: 'decathlon-fruit-jellies-citrus',
    brand: 'Decathlon',
    name: 'Energy Fruit Jellies Citrus',
    kind: 'jelly',
    serving: '1 bar, 25 g',
    sourceLabel: 'Decathlon',
    sourceUrl:
      'https://www.decathlon.co.uk/p/energy-fruit-jelly-ecosize-12x25g-citrus/311136/g4m8562277',
    nutrition: {
      ...EMPTY_NUTRITION,
      calories: 84,
      carbs: 21,
      sugar: 16,
      fat: 0.5,
      protein: 0.5,
      salt: 0.06,
      sodium: 24,
    },
  },
];

@Injectable({ providedIn: 'root' })
export class ProductService {
  readonly products = PRODUCTS;

  createEmptyQuantities(): ProductQuantities {
    return this.products.reduce(
      (quantities, product) => ({
        ...quantities,
        [product.id]: 0,
      }),
      {} as ProductQuantities,
    );
  }
}
